export const COMMAND_VALUE_CHANGE = 'COMMAND_VALUE_CHANGE';
export const NEW_GRID_COMMAND = 'NEW_GRID_COMMAND';
export const NEW_ROBOT_COMMAND = 'NEW_ROBOT_COMMAND';
export const MOVE_ROBOT_TO_LOCATION = 'MOVE_ROBOT_TO_LOCATION';